govuk-one-login/ipv-cri-dl-api

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/error/ErrorResponse.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/ThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/FormDataValidator.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ServiceFactory.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/ThirdPartyDocumentGatewayTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/FormDataValidatorTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationServiceTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ServiceFactoryTest.java
Treat as as non recoverable errors
- HTTP 400, seen when a client side encryption cert has expired
- All HTTP Status codes other than 200 and 429 (unless last connection retry)
- IpvCryptoException, seen when client signing verification cert expired, and all signature verification fails.
- FormDataValidator validation failing
Previously a user retry would be attempted in these scenarios with a CRI NP thrown when attempting to save attempts that never completed
FormDataValidator is renamed from PersonIdentityValidator to better fit its use (repurposed from fraudCRI)
- Main validation is on the front end, FormDataValidator is doing field presence checks
- Logging message changed to Validating form data...(Start), Form data validated. (Passed)
- If Form Data Validation fails, treated as non …
=> LIME 140 Improve Handling and logging of non-recoverable DCS related errors

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/error/ErrorResponse.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/HttpRetryer.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/ThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ServiceFactory.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/ThirdPartyDocumentGatewayTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationServiceTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ServiceFactoryTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandler.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandlerTest.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/metrics/Definitions.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/testdata/DocumentCheckTestDataGenerator.java
Added metrics to DL CRI DrivingPermitCheck Lambda
DrivingPermitCheck - Completed ok/error
Issue Credential - Completed ok/error
PermitCheckStatus - Verified, Retry, Unverified
FormDataValidator - pass/fail
Issuing Authority - DVA/DVLA
DCS Check Request - succeeded/failed
DrivingPermitCheck Contra Indicators - generated
HTTP Connection Send - request_created/send_ok/send_retry/send_error/send_max_retries/send_fail
DCS Response Type Fraud - ok/error
Add unit tests for status of document after an attempt (Verified, Retry, Unverified)
Metrics added to cover metrics requested for LIME-189
Definitions located in dl lib ...drivingpermit/library/metrics/Definitions.java.
- [LIME-189](https://govukverify.atlassian.net/browse/LIME-189)
=> LIME-189 Capture DL CRI Metrics

infrastructure/lambda/template.yaml
Added log subscription filters & removed provision concurrency configuration
For integration with splunk logging. 
Concurrency config temporarily removed for production teething issues, will need added back in once the CRI is more stable in prod
=> LIME-223 - Adding log subscription filters for splunk

.github/workflows/pre-merge-integration-test.yml, build.gradle, lambdas/issuecredential/build.gradle, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandler.java
(Merge after https://github.com/alphagov/di-ipv-cri-lib/pull/106)
Send CRI_END audit event when VC is being returned.
Add kms to issuecredential dependancies.
Update CRI lib version to 1.3.1
CRI_END audit event added per LIME-173.
Adding kms dependancy to issuecredential due to auto resolution failing with a locally generated cri lib.
CRI lib 1.3.1 contains the change needed.
- [LIME-173](https://govukverify.atlassian.net/browse/LIME-173)
=> LIME-173 send IPV_DRIVING_PERMIT_CRI_END audit event.

.github/workflows/pre-merge-integration-test.yml, .gitmodules, README.md, deploy.sh, infrastructure/lambda/private-api.yaml, infrastructure/lambda/public-api.yaml, infrastructure/lambda/template.yaml, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/VerifiableCredentialService.java, settings.gradle
- Removed `common-lambdas` git submodules
- Added new parameter overrides to the pre-merge-integration-tests workflow
- Updated the private/public api configuration to refer to the new common lambda functions
- Removed common resources from template.yaml
- Updated template.yaml to refer to common resources where necessary
- Updated VerifiableCredentialService to refer to new common verifiableCredentialKmsSigningKeyId SSM parameter
- Updated `deploy.sh` parameter-overrides to enable the stack to be deployed to the shared dev account
- To migrate to the common CRI framework and align with the kbv, address & fraud CRIs
- [OJ-999](https://govukverify.atlassian.net/browse/OJ-999)
[OJ-999]: https://govukverify.atlassian.net/browse/OJ-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> OJ-999 - Transition to common CRI framework

acceptance-tests/build.gradle, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/service/ConfigurationService.java, infrastructure/lambda/template.yaml
Add BE Driving Licence tests to repo
Lime-375-Add-BE-Driving-Licence-tests-to-repo-1
Proposed changes
Add the Driving Licence API test to the repo
-(https://govukverify.atlassian.net/jira/software/c/projects/LIME/boards/239?modal=detail&selectedIssue=LIME-375)
=> LIME-375: Driving Licence API test added to the structure

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicense.feature
These changes have been done as part of this ticket : https://govukverify.atlassian.net/browse/LIME-453
The test step "I click the Driving Licence CRI for the 'Build' environment" has been removed from the driving licence tests and has been replaced with the test step 'I click the Driving Licence CRI for the testEnvironment'. This is so that the test environment details are passed in the environment variables and not specified on the test step. This is to avoid duplication of tests.
=> Updated test step that clicks on Driving Licence CRI

.github/workflows/dailyDLSmokeTest.yml, .github/workflows/gradleBuildTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-integration-test.yml, acceptance-tests/Dockerfile
Pinned gradle version 7.6
Codebase supports gradle version 7.6
=> LIME-529 - Pinned gradle version 7.6

build.gradle, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/util/DocumentCheckPersonIdentityDetailedMapper.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/util/DocumentCheckPersonIdentityDetailedMapper.java
- audit event support added for `drivingPermit` data
- [LIME-440](https://govukverify.atlassian.net/browse/LIME-440)
See also: https://github.com/alphagov/di-ipv-cri-lib/pull/193
[LIME-440]: https://govukverify.atlassian.net/browse/LIME-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-440 - Capture Driving Licence issuer in TxMA Audit Events

.github/workflows/dailyDLSmokeTest.yml, .github/workflows/gradleBuildTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-integration-test.yml
Pinned gradle version 7.6
Codebase supports gradle version 7.6
=> LIME-529-2 - Updated gradle version from 7.3 to 7.6

infrastructure/lambda/template.yaml
Enabling VC expiry removal in production
So that IPV core and spot have more control on VC expiry
=> LIME-567: Enabling VC expiry removal in prod

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DVAEnterYourDetailsExactlyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVAEnterYourDetailsExactlyStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/WelshLangDrivingLicence.feature
This consists of the test changes done for LIME-520 'Ask users for their consent before DVLA check their driving licence details' and LIME-568 'Ask users for their consent before DVA check their driving licence details'.
Automation tests have been updated to now include the DVLA and DVA Consent check box. Tests have also been added to validate the Consent error message in the error Summary as well as on the checkbox. Welsh translation tests have also been updated. 
=> added tests for DVLA and DVA consent checkbox error validation

infrastructure/lambda/template.yaml
Add alarms for a concurrency threshold on DrivingPermitCheckLambda and IssueCredentialLambdambda via ConcurrentExecutions metrics
Added alarms for the common-api stack lambdas used by the deployed api stack (!sub via CommonStackName)- Session, Authorization and AccessToken
ProvisionedConcurrentExecutions is now also set to 1 in production for all DL Lambdas
To allow alerting if lambda concurrency is above the typically expected levels
- [LIME-628](https://govukverify.atlassian.net/browse/LIME-628)
[LIME-628]: https://govukverify.atlassian.net/browse/LIME-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-628 Add alarms for concurrency threshold on DrivingPermitCheckLambda and IssueCredentialLambda

infrastructure/lambda/template.yaml
Add DrivingLicenceLambdaInvocationDeviation alarm
Align AlarmDescriptions to use "Driving Licence"
DrivingLicenceLambdaInvocationDeviation to alert if the number of sessionInvocations is exceeding the number of issueCredentialInvocations by 50%
Fix inconsistency in CRI name for AlarmDescriptions
- [LIME-663](https://govukverify.atlassian.net/browse/LIME-663)
[LIME-663]: https://govukverify.atlassian.net/browse/LIME-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-663 Add DrivingLicenceLambdaInvocationDeviation alarm

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DLProveYourIdentityFullJourneyRoute.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature
Remove the existing test step where we validate the expiry date as 6 months from the current date
Add a new test step to validate that the exp date field is no longer available in the VCs in DL CRI
(https://govukverify.atlassian.net/browse/LIME-670)
=> Expiry Date should not be present in the VC test

acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationService.java
Correct the CI returned for checks that deem the document data to be not valid to `D02`
Amended acceptance test. 
The CI was incorrectly set as `DO2` (Delta Oscar Two) vs the correct `D02` (Delta Zero Two)
Incorrect CI value was also present in the acceptance tests
- [LIME-723](https://govukverify.atlassian.net/browse/LIME-723)
[LIME-723]: https://govukverify.atlassian.net/browse/LIME-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-723 Correct CI returned when document data is invalid

infrastructure/lambda/template.yaml, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ConfigurationService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dcs/DcsThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ConfigurationServiceTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationServiceTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandler.java
- Added support for document checking route.
- Refactored existing route for clarification.
- Change originally existed in now-redundant PR.
- [LIME-507](https://govukverify.atlassian.net/browse/LIME-507)
[LIME-507]: https://govukverify.atlassian.net/browse/LIME-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-507 - Added `HEADER_DOCUMENT_CHECKING_ROUTE` header to split path between DCS and DVAD.

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/dva/request/DvaPayload.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/dva/response/DvaResponse.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/error/ErrorResponse.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ConfigurationService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ThirdPartyAPIService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dcs/DcsCryptographyService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dcs/DcsThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaCryptographyService.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ConfigurationServiceTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/IdentityVerificationServiceTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaThirdPartyDocumentGatewayTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/util/HttpResponseUtils.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/util/MyJwsSigner.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/config/ParameterStoreParameters.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/metrics/Definitions.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/testdata/DrivingPermitFormTestDataGenerator.java
Added new methods to perform document checks to DVA directly and map the response to existing document check result. As a part of this the dvaPayload and dvaResponse models had to be updated to match the expected field names found in the request/response. 
To create request and response payloads that can be used in sending and receiving document check details to/from DVAs api and mapping them to the existing documentCheckResult model.
NOTE: The dvaResponse model is based off of what is expected to be found in the responses as defined in the documentation provided. I have incorporated a response that follows this into the DVA direct stub for now but some fields may need to be changed/added once we receive certificates and can connect to the real service.
=> LIME-685 - Creating call to DVA direct api

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/RequestHashValidator.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaThirdPartyDocumentGatewayTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/HashFactoryTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/RequestHashValidatorTest.java
Updated requestHash validator to discard requestId from request hash generation to make compatible with static responses being returned from the DVA imposter stub
request Id is unique per request, causing the generated request hash to be unique per request rather than per user. Due to the stub currently returning static responses for each test user of DVA, we need to be sure the request hashes included in the response from the stub match what is being sent to the stub/being generated in the Dl cri
=> LIME-506 - Removing requestId from reguest hash in lower envs

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/RequestHashValidator.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/HashFactoryTest.java
Updated hashFactory to use dateOfIssue for request hashing rather than issueDate
DVA uses dateOfIssue, DVLA use issueDate, the mismatch meant that there was a bug in the request hash being generated without a dateOfIssue
=> LIME-515 - Fixing request hashing to use dateOfIssue

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DVAEnterYourDetailsExactlyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/TestDataCreator.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature
Align test user Kenneth with DVLA test data
Switch to using Kenneth for Happypath tests
~Removed assert on vc exp in several tests.~ Restored pending feature flag retirement 
To allow testing DCS and DVLA via the same ac tests
~Assert always fails in dev.~
- [LIME-765](https://govukverify.atlassian.net/browse/LIME-765)
[LIME-765]: https://govukverify.atlassian.net/browse/LIME-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-765 Update Kenneth details and use Kenneth for happy path

lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/config/ParameterStoreParameters.java
Updating the names of the DCS certificates
DCS are performing a certificate rotation of the following certificates
EncryptionCertForDrivingPermitToEncrypt
SigningCertForDrivingPermitToVerify
This will require the following parameters to be updated in DL CRI
/DCS/JWE/signingCertForDrivingPermitToVerify
/DCS/JWE/encryptionCertForDrivingPermitToEncrypt
For a breakdown of the certificates see [4.2.6.1. DCS Certificate Catalogue](https://govukverify.atlassian.net/wiki/spaces/PYI/pages/3567485402/4.2.6.1.+DCS+Certificate+Catalogue)
=> LIME-837: Updating certificate names for DCS certificates

lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/config/ParameterStoreParameters.java
Renaming received DCS certificates to allow change over in prod
To check differences and force redeploy of certificates
=> LIME-837: Updating cert names for prod rotation

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/util/SleepHelper.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/util/SleepHelperTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandler.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/metrics/Definitions.java
Recovery redirect added when users have submitted the form but are over max attempts.
Added metric for when the max attempt redirect happens.
Remove Thread.sleep() version of sleep helper.
Log the Exception class in IssueCredentialHandler generic catch
A review of DL api errors shows the max attempt error as the most common, it was treated correctly as as an error. For same scenario in passport-v1 it was discovered that it possible to safely recover the user and mitigate entirely this scenario, this is now done for dl.
The Thread.sleep(), version of the backoff will never be used again and is safe to remove.
It will also remove a sonar warning.
Logging the generic exception in IssueCredentialHandler is suppressed to avoid any PII output, but the class type should be logged to aid error …
=> LIME-767 Redirect users over max attempts.

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/VerifiableCredentialConstants.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/verifiablecredential/Evidence.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/util/EvidenceHelper.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/VerifiableCredentialServiceTest.java
Correct VC evidence type key
Value was mapped as the enum value rather than the intended string name.
- [LIME-865](https://govukverify.atlassian.net/browse/LIME-865)
[LIME-865]: https://govukverify.atlassian.net/browse/LIME-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-865 Correct VC evidence type key

acceptance-tests/src/test/resources/Data/DVAValidJsonPayload.json, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature, infrastructure/lambda/template.yaml, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java
Removed document Checking route header logic for thirdPartyApiSelection as no longer needed post go live, aligned tests with this updated logic, updated dvaDirectEnabled mappings in template. 
All of this will result in users being routed to the new dvaDirectRoute once in prod
=> LIME-750 - Dva direct Go live updates

acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java
Removed the logic from the DL CRI which allows failed checks to fall back to DCS
Direct connections have been live for a week now without issue so dynamic fallbacks are no longer required
=> LIME-867: Removing the fallback logic for DL CRI

acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicense.feature
Removed set document checking route
So that tests can pass following merge of LIME-864
=> LIME-864: Removed remaining set document checking route

infrastructure/lambda/template.yaml
Removed 4XX alarm from template
So that we are no longer running P1 alerts for 400's in production
=> LIME-862: Removing the 4XX alarm from the DL CRI

lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/config/ParameterStoreParameters.java
Updated certificate names for root and intermediate certs
So that we can use new certificates in prod but maintain the ability to rollback
=> LIME-888: Updating the DVA root and intermediate certs

infrastructure/lambda/template.yaml
Updated event that triggers lambda to try and avoid creating a new role (pipeline permissions do not allow for new role creation)
=> LIME-498 - Updating template

acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dvla/DvlaThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/util/RequestSentAuditHelper.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dvla/DvlaThirdPartyDocumentGatewayTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/util/RequestSentAuditHelperTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/util/EvidenceHelper.java, lib-dvla/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dvla/exception/DVLAMatchUnauthorizedException.java, lib-dvla/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dvla/service/endpoints/DriverMatchService.java, lib-dvla/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dvla/service/endpoints/TokenRequestService.java, lib-dvla/src/test/java/uk/gov/di/ipv/cri/drivingpermit/library/dvla/service/endpoints/DriverMatchServiceTest.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/error/ErrorResponse.java
Added handling of an edge case where a token may have been invalidated remotely before the expected expiration time.
Should this happen a recovery mechanism will attempt to retrieve a new token and make one more match attempt.
To avoid failing the users attempt, should this occur at the inopportune time of the token being invalidated while being used in a match request.
- [LIME-768](https://govukverify.atlassian.net/browse/LIME-768)
[LIME-768]: https://govukverify.atlassian.net/browse/LIME-768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-768 Implement recovery for token expiration during use

infrastructure/lambda/template.yaml
Increase api rate/burst limits and lambda cpu allocation
API limits increased to match address-ap/core-back as a fix is being prepared in dl-front that should enable front autoscaling, which should have an increase in traffic against both private/public apis.
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-727 Increase DL API Throttle/Throttling limits

acceptance-tests/Dockerfile
Update ac test image to JDK17 and Gradle8
The pipeline test step is attempting to use gradle7.6 and jdk11 for the ac tests.
- [LIME-844](https://govukverify.atlassian.net/browse/LIME-844)
[LIME-844]: https://govukverify.atlassian.net/browse/LIME-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-844 Update ac test image to JDK17 and Gradle8

infrastructure/lambda/template.yaml
Updated the template so that the initial secret value is read from the param and so that the rotation does not happen immediately in higher envs
To allow the release and secret rotation to be decoupled
- [LIME-769](https://govukverify.atlassian.net/browse/LIME-769)
[LIME-769]: https://govukverify.atlassian.net/browse/LIME-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-769: Updating secret rotation to not happen on deployment or secret change and toggled off implementation in integration and prod

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceAPIStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature, build.gradle, infrastructure/lambda/template.yaml
Enabling JTI token field to appear in VC, and adding this check to acceptance checks.
To align with other CRIs and enable use of JTI for unique referencing.
- [LIME-569](https://govukverify.atlassian.net/browse/LIME-569)
[LIME-569]: https://govukverify.atlassian.net/browse/LIME-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-569 adding jti field to VC

lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/IssueCredentialHandlerTest.java
Added ability to specify pact version.
To ensure we are pointed at the correct version in future and avoid failing to find pact.
- [LIME-989](https://govukverify.atlassian.net/browse/LIME-989)
[LIME-989]: https://govukverify.atlassian.net/browse/LIME-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-989 adding consumer version for pact testing

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/BrowserUtils.java
The value of "lang" has been edited to "lng" in acceptance-tests.
The value has been changed in common-express. As our front end was changed for the language toggle, this change is required for our api tests to be aligned for this value.
- [LIME-1069](https://govukverify.atlassian.net/browse/LIME-1069)
=> LIME-1069 aligning lng cookie value in tests

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/Welsh/WelshLangDrivingLicence.feature
- Added language toggle test to check language toggle works from English to Welsh  for both DVLA & DVA
- Added language toggle test to check language toggle works from Welsh to English for both DVLA & DVA
To add coverage for a new shared component called [one login language toggle](https://www.npmjs.com/package/@govuk-one-login/one-login-language-toggle) 
- [LIME-1069](https://govukverify.atlassian.net/browse/LIME-1069)
[LIME-1069]: https://govukverify.atlassian.net/browse/LIME-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1069 - Added language Toggle Test

.github/workflows/pre-merge-checks.yml, .pre-commit-config.yaml, .secrets.baseline, README.md
- Added pre-commit GHA workflow step
- Added pre-commit-config with `detect-secrets`
- Added secrets.baseline with `detect-secrets scan --slim > .secrets.baseline`
- As per ticket requirements
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-487: Add pre-commit GHA workflow and pre-commit-config

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java
Updated DrivingLicenceAPIPage to use ClientID values
Added the ClientID Value for Driving Licence API Tests
This captures the ClientId found in the session response and uses it in the later auth code request call
- [LIME-1115](https://govukverify.atlassian.net/browse/LIME-1115)
[LIME-1115]: https://govukverify.atlassian.net/browse/LIME-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1115]: https://govukverify.atlassian.net/browse/LIME-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1115 - Add ClientID to Driving Licence API Page for API Tests

.github/workflows/run-pre-merge-integration-tests.yml, .github/workflows/smoke-test-build.yml, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/runners/TestRunner.java, acceptance-tests/src/test/resources/cucumber.properties
Disabled auto-reporting via the following 
Add cucumber.properties with the following contents
- cucumber.publish.quiet=false to ensure reporting if re-enabled is visible
- cucumber.publish.enabled=false to stop the reporting.
Removed env-var CUCUMBER_PUBLISH_ENABLED: true from git hub actions
Change publish to false in @CucumberOptions in the test runner.
To disable sending reports to a third-party
- [LIME-1212](https://govukverify.atlassian.net/browse/LIME-1212)
[LIME-1212]: https://govukverify.atlassian.net/browse/LIME-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1212 Disable cucumber report publishing

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/runners/TestRunner.java, acceptance-tests/src/test/resources/cucumber.properties
Remove cucumber publish variable
A previous PR set the publish value to false to disable the report publishing.
The presence of the variable is however is still being flagged.
- [LIME-1212](https://govukverify.atlassian.net/browse/LIME-1212)
[LIME-1212]: https://govukverify.atlassian.net/browse/LIME-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1212 Remove references to cucumber publish

.github/workflows/run-sonar-scan.yml, .github/workflows/run-unit-tests.yml, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, build.gradle, infrastructure/lambda/template.yaml, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/VerifiableCredentialService.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/utils/PreLambdaHandler.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/VerifiableCredentialServiceTest.java
Updated verifiableCredentialService to use updated jwtSigning implementation and include kid in jwt headers
=> LIME-1201 - Including Opaque KID in JWT headers for VCs

infrastructure/lambda/template.yaml
Setting ActionsEnabled to true for newly deployed alarms. 
Enabling alarms from [this PR](https://github.com/govuk-one-login/ipv-cri-dl-api/pull/198)
When ActionsEnabled is set to true when first deploying alarms, it creates slack notifications. As we don't want slack notifications in production, alarms have been switched off in the initial deployment and now switched on.
- [IPS-655](https://govukverify.atlassian.net/browse/IPS-655)
[IPS-655]: https://govukverify.atlassian.net/browse/IPS-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-655 enabling alarms

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandler.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/IssueCredentialHandlerTest.java
SessionNotFoundException added to both Driving Permit Handler and Issue Credential handler. Corresponding unit tests also created.
To ensure scenarios where a user has no session id are identified promptly and the correct error is returned.
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
PR for equivalent changes in passport CRI has been completed [here](https://github.com/govuk-one-login/ipv-cri-uk-passport-api/pull/169)
PR for equivalent changes in fraud CRI has been completed [here](https://github.com/govuk-one-login/ipv-cri-fraud-api/pull/326)
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1114 SessionNotFoundExceptions added to handlers

acceptance-tests/build.gradle, build.gradle
Nimbus JWT and Oauth dependencies updated in line with Fraud CRI and Passport CRI following equivalent Dependabot PRs being created for those CRIs.
No Jira ticket but related to [this Fraud Dependabot PR](https://github.com/govuk-one-login/ipv-cri-fraud-api/pull/328) and [this Passport Dependabot PR](https://github.com/govuk-one-login/ipv-cri-uk-passport-api/pull/171)
=> Updating nimbus jwt and oauth in line with other LIME CRIs

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java
Issue during testing where an empty value for the session_id header was returning Unexpected server error.
Update CheckPassportHandler.java to use UUID so it catches incorrect strings/special chars
Added UUID check for sessionID in CheckPassportHandler.java
Added unit test for invalid sessionID in CheckPassportHandlerTest.java
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
- [LIME-1289](https://govukverify.atlassian.net/browse/LIME-1289)
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1289]: https://govukverify.atlassian.net/browse/LIME-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIME-1114] Added sessionID validation UUID check

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceAPIStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVACRIAPI.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLACRIAPI.feature
to check that when a invalid sessionid is sent to the driving licence endpoint, or authcode is sent in credential issuer endpoint
Added new acceptance-tests to DVA and DVA Api tests
To add coverage to the changes made in LIME-1114 around incoming session_id header is not null
- [LIME-1114](https://govukverify.atlassian.net/browse/LIME-1114)
All New tests passed locally:
All existing tests passing locally: 
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1114]: https://govukverify.atlassian.net/browse/LIME-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1114: Added new API Acceptance tests

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/UniversalSteps.java
Log the page content when an ac-test title match fails
To enable additional context for the source of the test failure
=> BAU-LogErrorPages Log the page content when title match fails

acceptance-tests/run-dev-perf-test.sh, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/UniversalStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/Driver.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLACRIAPI.feature
Add dev perf test script.
Correctly clean up after each ac test.
- Move "400 CannotBeFound" scenario into a separate test now that it is being handled correctly by the stub
- Note this commit removes the sleep in driver.get()
To allow a faster build and test iteration with-out involving a full formal perf test.
Ac test where leaving the driver open, leaving lots of browsers open after the test.
This change closes the driver after each test using in built cucumber support.
The CannotBeFound scenario is now being retuned as expected from the stub and is being handled correctly in the happy path by the CRI.
- [LIME-1208](https://govukverify.atlassian.net/browse/LIME-1208)
[LIME-1208]: https://govukverify.atlassian.net/browse/LIME-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> LIME-1208 Add dev perf test script and correctly clean up after each ac test

acceptance-tests/build.gradle, build.gradle, lambdas/certexpiryreminder/build.gradle, lambdas/drivingpermitcheck/build.gradle, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ThirdPartyAPIServiceFactory.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ThirdPartyAPIServiceFactoryTest.java, lambdas/issuecredential/build.gradle, lambdas/passwordRenewal/build.gradle, lambdas/passwordRenewal/src/main/java/uk/gov/di/ipv/cri/drivingpermit/event/handler/PasswordRenewalHandler.java, lib-dva/build.gradle, lib-dvla/build.gradle, lib-dvla/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dvla/service/DvlaEndpointFactory.java, lib/build.gradle, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/service/DocumentCheckResultStorageService.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/service/ServiceFactory.java
CRI
- Correct floating aws sdk client components versions causing runtime failures (java.lang.IncompatibleClassChangeError)
- - clients ssm, secretsmanager, appconfigdata
- exclude un-needed url-connection-client from being packaged.
- Correct using a dedicated DynamoDbEnhancedClient for all Datastores instead of a shared DynamoDbEnhancedClient.
Ac Tests
- Update cri_common_lib_version to 3.1.3 in ac tests
- Link aws_powertools_logging_version, aws_powertools_metrics_version and aws_powertools_parameters_version to aws_powertools_version in ac test
- Remove aws_embedded_metrics_version from ac test
- Link cucumber_junit_version and cucumber_version to java_cucumber_version in ac tests.
- Update selenium_version, axe_core_selenium_version and webdrivermanager_version
To correct a version …
=> LIME-1312 Update to CRI lib 3.1.3

acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
Currently the feature-flag for Auth Source is disable in Staging
Tests for Auth Source have been updated to remove the Tags that allow running in Staging
- [LIME-1365](https://govukverify.atlassian.net/browse/LIME-1365)
[LIME-1365]: https://govukverify.atlassian.net/browse/LIME-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1365 - Update Auth Source Test Tags to disable running in Staging environment

acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
commented out the @uat test tag on the auth source post-merge tests
- [LIME-1366](https://govukverify.atlassian.net/browse/LIME-1366)
[LIME-1366]: https://govukverify.atlassian.net/browse/LIME-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1366]: https://govukverify.atlassian.net/browse/LIME-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1366 - Update Auth Source Test Tags to disable running in Staging environment - UAT Tag

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/Data/DVAAuthSourceInvalidBillyJsonPayload.json, acceptance-tests/src/test/resources/Data/DVAAuthSourceInvalidKennethJsonPayload.json, acceptance-tests/src/test/resources/Data/DVLAAuthSourceInvalidKennethJsonPayloadNoAddress.json, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVACRIAPI.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLACRIAPI.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
LIME-1367: 
New Tests added to cover extra happy path and unhappy path scenarios
Across both API Pre-merge tests
And UI Post-merge tests
- [LIME-1367](https://govukverify.atlassian.net/browse/LIME-1367)
API Pre-merge tests Passed Locally:
UI Post-merge tests passed locally:
[LIME-1367]: https://govukverify.atlassian.net/browse/LIME-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1367: DL Auth Source - Update API and UI Tests

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
Changes made to auth source feature tests to ensure they correctly test DL auth source consent screen. 
All auth source feature tests now passing correctly. 
The tests in question had been created prior to the DL auth source consent screen being created so some tweaking of the tests was required once the consent screen had been created. 
- [LIME-1328](https://govukverify.atlassian.net/browse/LIME-1328)
[LIME-1328]: https://govukverify.atlassian.net/browse/LIME-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1328/test LIME-1367: auth source tests amended

acceptance-tests/src/test/resources/Data/DVAAuthSourceInvalidJsonPayload.json, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVACRIAPI.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLACRIAPI.feature
Updated API Tests for Auth Source - Scenario for Retry for DVA and DVLA now pass as expected
Updated FE Tests for Auth Source - Scenario for Postcode mismatch on UAT Staging environment added and split from the Smoke/ Build Test
- [LIME-1383](https://govukverify.atlassian.net/browse/LIME-1383)
[LIME-1383]: https://govukverify.atlassian.net/browse/LIME-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1383: Updated Failing API Retry Test and Failing UAT Postcode validation FE Test

acceptance-tests/build.gradle, build.gradle, lambdas/certexpiryreminder/build.gradle, lambdas/drivingpermitcheck/build.gradle, lambdas/issuecredential/build.gradle
The purpose of this change would be to reduce the number of Nimbus dependencies that require updating and to remove the risk of conflict that exists in having a dependency that is already a sub-dependency.
removed jwt_version from build.gradle
- [LIME-1291](https://govukverify.atlassian.net/browse/LIME-1291)
[LIME-1291]: https://govukverify.atlassian.net/browse/LIME-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1291 Consolidate Nimbus dependencies 

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature
- Switched to Kenneth for HappyPath tests.
- Switched to Kenneth where appropriate for unhappy path tests.
- Untagged test that are not valid against the UAT due to miss-matched test users
- Fix for race condition checking the cookie banner before it is loaded.
To match thirdparty uat test users.
=> LIME-1520 DVA AC test fixes

infrastructure/lambda/private-api.yaml, infrastructure/lambda/public-api.yaml
Changes the uri used for invoking the common-api lambdas to invoke on the lambda alias
To complete the setup of provisioned concurrency for the common-lambdas
=> LIME-1520 Enable Provisioned Concurrency in Common-API Lambdas

acceptance-tests/run-traffic-tests.sh, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
Tag only tests that are expected to result in a VC for canary traffic tests
- Enable 1 more loop of the ac test to account for reduced tagged tests.
Error scenarios where being ran as part of the traffic test, causing canaries to auto roll back.
=> LIME-1520 Tag only tests that are expected to result in a VC for canary traffic tests

lambdas/personInfo/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/PersonInfoHandler.java
Fix crash due to invalid chars in OAuth response
An exception was being return in the OAuth Error.
=> LIME-1520 Fix Illegal chars in OAuth response

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
Update AC tests to assert correct error message and add assertURLContains to check the VC page has loaded before reading contents.
The error message has change to the Nimbus message.
(assertURLContains) To address flakiness due to a race condition in the tests, where the VC content is being read before the VC page has loaded -  brought in from fraud https://github.com/govuk-one-login/ipv-cri-fraud-api/blob/987ffedf875aee3115612f14c6e0ffa35bb2f865/acceptance-tests/src/test/java/gov/di_ipv_fraud/pages/FraudPageObject.java#L222
=> LIME-1520 Update AC test to assert correct error message

.github/dependabot.yml
Changes made to:
1. Update grouping in dependabot.yml to ensure dependencies that are required to be kept at the same version number as each other are updated together by dependabot automatically rather than creating an individual PR for each dependency.  
2. Update dependabot open PR limit to 20 due to present limit of 5 being too few given some PRs can be blocked for some time. 
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1229 updates dependabot grouping and PR limit

.secrets.baseline, acceptance-tests/build.gradle, acceptance-tests/settings.gradle, acceptance-tests/src/test/resources/features/UKDrivingLicence/Common/DLCommon.feature, build.gradle, infrastructure/lambda/template.yaml, lambdas/build.gradle, lambdas/certexpiryreminder/build.gradle, lambdas/certexpiryreminder/src/main/java/uk/gov/di/ipv/cri/drivingpermit/certreminder/handler/CertExpiryReminderHandler.java, lambdas/drivingpermitcheck/build.gradle, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/dva/DvaThirdPartyDocumentGatewayTest.java, lambdas/issuecredential/build.gradle, lambdas/passwordRenewal/build.gradle, lambdas/passwordRenewal/src/main/java/uk/gov/di/ipv/cri/drivingpermit/event/handler/PasswordRenewalHandler.java, lambdas/personInfo/build.gradle, lib-dva/build.gradle, lib-dva/src/main/resources/log4j2.xml, lib-dvla/bin/main/log4j2.xml, lib-dvla/build.gradle, lib/build.gradle, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/service/ServiceFactory.java, lib/src/main/resources/log4j2.xml, settings.gradle
Add OpenTelemetry instrumentation re-work gradle builds and Java dependencies
- Enable Java language linting to aid detection of code-smells (warn only)
- Add Dynatrace logging (enabled in non-pipeline stacks only)
- Decoupled AC test from CRI Gradle builds
- Added Jackson bom
- Updated Mockito from V4 to V5
- Use ACM Client now provided by CRI 4.0.0
Add tracing instrumentation to AWS SDK clients.
Correct issues with the AspectJ code weaving setup.
Simplify Jackson dependancy resolution.
Resolve a blocker preventing automatic Mockito updates (dependancies changes)
- [LIME-1540](https://govukverify.atlassian.net/browse/LIME-1540)
[LIME-1538]: https://govukverify.atlassian.net/browse/LIME-1538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> LIME-1540 Add OpenTelemetry instrumentation re-work gradle builds and Java dependencies

infrastructure/lambda/template.yaml
Create an alarm to identify DVA third party api errors.
Added alarm (DVAThirdPartyApiErrorAlarm) definition to template.yaml
The aim is to be able to trace errors to the DVA api
Alarm configuration was tested by writing to the metric using an aws cli command (see [LIME-1203](https://govukverify.atlassian.net/browse/LIME-1203) for details).
- [LIME-1203](https://govukverify.atlassian.net/browse/LIME-1203)
[LIME-1203]: https://govukverify.atlassian.net/browse/LIME-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1203 custom metric alarm created for DVA

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DLProveYourIdentityFullJourneyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVAEnterYourDetailsExactlyStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/Common/DLCommon.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVAProveIdentityFullJourney.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLAProveIdentityFullJourney.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/Welsh/WelshLangDrivingLicence.feature
serviceName amended to remove _"... - Prove your identity" from page tab titles in DL FE. BE tests updated to reflect this and the removal adding of 'One Login' to the pageTitle suffix brought in by the Common Express update.
To keep this service in line with other services of the programme and fix failing tests as a result of the Common Express update beyond 10.1.x.
- [LIME-1591](https://govukverify.atlassian.net/browse/LIME-1591)
[LIME-1508]: https://govukverify.atlassian.net/browse/LIME-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1591]: https://govukverify.atlassian.net/browse/LIME-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1508 corrected pageTitle and tests

infrastructure/lambda/template.yaml
Prod and non-prod alarms differentiated in order to direct non-prod alarms to the lime-critical-alarm-nonprod Slack channel. 
- [LIME-941](https://govukverify.atlassian.net/browse/LIME-941)
[LIME-941]: https://govukverify.atlassian.net/browse/LIME-941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-941 prod and non-prod alarms differentiated

acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicenceAuthSource.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicenceAuthSource.feature
Handle race conditions within DL Auth source AC tests
To reduce pipeline failures.
- [LIME-1599](https://govukverify.atlassian.net/browse/LIME-1599)
[LIME-1599]: https://govukverify.atlassian.net/browse/LIME-1599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1599 Handle race conditions within DL Auth source AC tests.

.github/workflows/run-pre-merge-integration-tests.yml, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/domain/Strategy.java
Add support for new ipv-core client id - "ipv-core-3rd-party-stubs"
Fix pre-merge sam build step missing sam-version: "1.134.0" pinning
ipv-core-3rd-party-stubs - To enable an IPV-Core end to end journey with CRI using third-party stubs
- [LIME-1626](https://govukverify.atlassian.net/browse/LIME-1626)
- depends on https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/441
[LIME-1626]: https://govukverify.atlassian.net/browse/LIME-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1626 Add support for new ipv-core client id - "ipv-core-3rd-party-stubs"

infrastructure/lambda/template.yaml
Disabled Provisioned Concurrency for DL, this PR should be merged before the fast follow which enables snapstart -https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/444
=> LIME-1441 - Disabling ProvisionedConcurrency for DL (dev-staging)

infrastructure/lambda/template.yaml
Disabling provisionedConcurrency for DL integration/Production. Fast follow to this PR being merged should be to enable snapstart for Integration/production
=> LIME-1443 - Disabling ProvisionedConcurrency for DL (int/Prod)

lambdas/certexpiryreminder/src/main/java/uk/gov/di/ipv/cri/drivingpermit/certreminder/config/CertExpiryReminderConfig.java, lambdas/certexpiryreminder/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/config/CertExpiryReminderConfigTest.java
Removed unused parameter reads from certExpiryLambda. TLSIntermediate cert is no longer held by DVA and therefore parameter and reference in certExpiryLambda has been removed as part of this PR
=> LIME-1669 - Removing unused parameter reads from certExpiryLambda

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/exception/DocumentCheckResultItemNotFoundException.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/exception/PersonIdentityDetailedNotFoundException.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/exception/SessionItemNotFoundException.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandler.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/IssueCredentialHandlerTest.java, lambdas/personInfo/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/PersonInfoHandler.java, lambdas/personInfo/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/PersonInfoHandlerTest.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/logging/LoggingSupport.java
clearPersistentJourneyKeys at the start of each lambda.
Add null checks on sessionId header to personInfo.
Improve null checks around lambda input headers.
Add null checks to DynamoDb returned items.
Catch known common-api exceptions to log their occurrences.
Aligned IssueCredential exception handling between Fraud, DL and Passport
clearPersistentJourneyKeys to avoid using latched keys in logs prior to them being set by the session service.
SessionId header null checks for parity with the other lambdas and aid tracking of issues.
Input headers may not be present.
DynamoDB can return null objects and this is suspected to be the cause of low frequency null pointer.
The known common-api exceptions being caught and log is to aid diagnoses of null returned items prior to implementing retries. …
=> LIME-1662 Increase logging clarity in error pathways and unexpected conditions

build.gradle
Update to CRI-Lib 5.2.1
To bring in retries on getSessionByAccessToken
- [LIME-1683](https://govukverify.atlassian.net/browse/LIME-1683)
[LIME-1683]: https://govukverify.atlassian.net/browse/LIME-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1683 Update to CRI-Lib 5.2.1

infrastructure/lambda/template.yaml
Add AlarmsEnabled condition to alarms missed by previous PR
Previous PR - https://github.com/govuk-one-login/ipv-cri-dl-api/pull/492  the intention was to not have alarms enabled in non-pipeline stacks however 2 alarms where missed.
- [LIME-1665](https://govukverify.atlassian.net/browse/LIME-1665)
[LIME-1665]: https://govukverify.atlassian.net/browse/LIME-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1665 Add AlarmsEnabled condition to alarms missed by previous PR

.github/workflows/post-merge-package-for-build.yml
Removing manual github actions trigger for a deploy to build.
Could erroneously deploy a branch to build which could propagate up to prod.
- [LIME-1845](https://govukverify.atlassian.net/browse/LIME-1845)
[LIME-1845]: https://govukverify.atlassian.net/browse/LIME-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1845: Remove manual trigger for package for build github actions pipeline

build.gradle
aws powertools version from 1.20.1 to 1.18.0
- [LIME-1889](https://govukverify.atlassian.net/browse/LIME-1889)
[LIME-1889]: https://govukverify.atlassian.net/browse/LIME-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1889 Revert aws powertools version to 1.18.0

infrastructure/lambda/template.yaml
Directed the prod cert expiry alarm away from di-2nd-line channel as this has been firing daily and producing pager duty notifications. Work to rotate the certificates is in progress under - [LIME-1827](https://govukverify.atlassian.net/browse/LIME-1827)
Once the certs are rotated, consideration will be given to reverting this change or leaving as is.
- [LIME-1904](https://govukverify.atlassian.net/browse/LIME-1904)
[LIME-1827]: https://govukverify.atlassian.net/browse/LIME-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1904]: https://govukverify.atlassian.net/browse/LIME-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1904 Redirect cert expiry alarm away from di-2nd-line
