govuk-one-login/ipv-cri-dl-api

build.gradle, lambdas/drivingpermitcheck/build.gradle, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/DcsPayload.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/DocumentCheckResult.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/DocumentCheckVerificationResult.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/DocumentVerificationResponse.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/DrivingPermitForm.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/ThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/issuecredential/build.gradle, settings.gradle
Added retry logic for DCS requests in Driving licence FE, also added the accessDenied error for routing users back to IPV core who have escaped in driving licence
=> LIME-147 - Adding retry logic and accessDenied Oauth error

infrastructure/lambda/template.yaml
Updated to reference folders in template rather than zips
To fix the broken github actions following common lib changes
=> LIME-147: Fixing issue where common lambdas no longer create zips

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-integration-test.yml, .gitmodules, README.md, deploy.sh, infrastructure/lambda/template.yaml, lambdas/drivingpermitcheck/build.gradle, lambdas/issuecredential/build.gradle
- Updates to use sam build to compile the code
- To fix the direct deployment to the informal `dev` environment
=> fix local dev deployment

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/gateway/ThirdPartyDocumentGateway.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java
Updated logging for Driving licence
For tracking and debugging driving licence requests to DCS
=> LIME-141 - Updating DL logs

infrastructure/lambda/private-api.yaml, infrastructure/lambda/public-api.yaml, infrastructure/lambda/template.yaml
Renamed public and private apis
Added alerts
To allow us to be notified if the service is experiencing issues
- [LIME-211](https://govukverify.atlassian.net/browse/LIME-211)
=> LIME-211: Renaming apis and adding alerts

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceAPIStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature
Added backend tests for Driving Licence CRI
Commented out tests that dont pass until bug can be fixed
To enable the pipeline and pre merge integration tests to continue
=> LIME-375: Added backend tests for DL

.github/workflows/dailyDLSmokeTest.yml, .github/workflows/gradleBuildTest.yml, acceptance-tests/build.gradle, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicense.feature
These changes are part of JIRA ticket https://govukverify.atlassian.net/browse/LIME-434
Added dailyDLSmokeTest.yml and gradleBuildTest.yml to github workflows.
Added Allure Workflow steps to dailyDLSmokeTest.yml
=> Lime 434 DL allure reports to GitHub pages

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DVAEnterYourDetailsExactlyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/WelshLangDrivingLicence.feature
Add consent box to acceptance tests
To enable the test pack to continue passing for other tickets
=> LIME-520: Fixing existing integration tests by adding consent box

.github/workflows/post-merge-deploy-to-dev.yml
- `role-to-assume` value  updated to current values
- 
=> HOTFIX - role-to-assume updated

acceptance-tests/src/test/resources/features/UKDrivingLicence/WelshLangDrivingLicence.feature
Updated Acceptance test for neu spelling correction
To reflect the change in DL frontend
=> LIME-655 - Updated Acceptance test for neu spelling correction

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVAEnterYourDetailsExactlyStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicense.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/WelshLangDrivingLicence.feature
Updated DL acceptance test for page titles
To include the change to the service name in the DL frontend
=> LIME-650 - Acceptance test updated for driving licence for page titles

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVAEnterYourDetailsExactlyStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/WelshLangDrivingLicence.feature
This Pr contains 3 bug fixed testing
https://govukverify.atlassian.net/browse/LIME-656
https://govukverify.atlassian.net/browse/LIME-657
https://govukverify.atlassian.net/browse/LIME-658
Proposed changes
DVLA Welsh Issue Number Validation Bug
DVA Welsh Licence Number (Symbols) Validation Bug
Welsh Issue Date Validation Transcription Bug DVA
What changed
Test added in the scenarios
DVLA Issue number field error message in Welsh
DVA Licence number field error message in Welsh
DVA Driving Licence Issue date field error message in Welsh
=> Bug646,657,658

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DLProveYourIdentityFullJourneyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DLProveYourIdentityFullJourneyStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/TestDataCreator.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DLProveYourIdentityFullJourneyRoute.feature
Automation tests have been added to cover the end to end journey testing on the Orchestrator stub full journey route using driving licence as the photo Id in Staging environment.
The JIRA ticket for this work is https://govukverify.atlassian.net/browse/LIME-536
=> Lime 536 integration testing with ipv core and spot

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/DrivingLicenceSubject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/TestDataCreator.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature
Added tests to verify updated licence number regex accepts details for edge cases
=> LIME-662 - adding tests for licence number validation edge cases

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicense.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/WelshLangDrivingLicence.feature
DL Bug - Rejecting Cookie Banner
https://govukverify.atlassian.net/browse/LIME-665
Cookie banner Typo
You’ve rejected additional cookies. You can change your cookie settings at any time.
=> DL Chrome Console Bug-Reject Analysis cookie 

infrastructure/lambda/template.yaml
sizing of deployment infrastructure in the cfn template
Updating build configuration to match production for the performance testing 
- [LIME-698](https://govukverify.atlassian.net/browse/LIME-698)
[LIME-698]: https://govukverify.atlassian.net/browse/LIME-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> lime-698 update scaling for performance testing

acceptance-tests/src/test/resources/features/UKDrivingLicence/DLProveYourIdentityFullJourneyRoute.feature
DL Prove Your identity Full journey changed the failing test
=>  DLIntegrationTestStepsFix

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ServiceFactory.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ServiceFactoryTest.java
Reducing parameters of constructors in serviceFactory/DrivingPermitHandler
=> LIME-682 service factory updates

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DVAEnterYourDetailsExactlyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/TestDataCreator.java
Updated tests to work with new issue dates following the changes on LIME-771
=> LIME-771: Updating tests to use new issue date values

build.gradle
IPS-310 Sonarcloud Migration
IPS-310 Sonarcloud Migration
- [1PS-310](https://govukverify.atlassian.net/browse/IPS-310)
=> IPS-310 Sonarcloud Migration to govuk-one-login

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/model/DrivingPermitForm.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceAPIStepDefs.java, acceptance-tests/src/test/resources/Data/DVLA-DCS-InvalidJsonPayload.json, acceptance-tests/src/test/resources/Data/DVLAServerErrorInvalidJsonPayload.json, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/metrics/Definitions.java
Added logic to fall back to DCS in the scenario we experience any issues with DVLA
To ensure the service continues to perform as expected during early live support
=> LIME-838: Adding fail over logic for DVLA go live

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/model/DrivingPermitForm.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceAPIStepDefs.java, acceptance-tests/src/test/resources/Data/DVLA-DCS-InvalidJsonPayload.json, acceptance-tests/src/test/resources/Data/DVLAServerErrorInvalidJsonPayload.json, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicenceCRIAPI.feature, lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/metrics/Definitions.java
Restoring fail over that was reverted in govuk-one-login/ipv-cri-dl-api#117
=> Restoring "LIME-838: Adding fail over logic for DVLA go live""

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DLProveYourIdentityFullJourneyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DeviceSelectionPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/GlobalPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/ProveYourIdentityGovUkPage.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/LoginSteps.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/utilities/PageObjectSupport.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DLProveYourIdentityFullJourneyRoute.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DrivingLicense.feature
E2E tests that use the orchestrator stub full journey route have been failing on some test steps. These test steps have been fixed.
=> LIME-839-fixed the failing steps on E2E tests

infrastructure/lambda/template.yaml
IPS-291 add changes for dynatrace integration
IPS-291 add changes for dynatrace integration
- [IPS-291](https://govukverify.atlassian.net/browse/IPS-291)
[IPS-291]: https://govukverify.atlassian.net/browse/IPS-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-291 add changes for dynatrace integration

infrastructure/lambda/template.yaml, lambdas/certexpiryreminder/src/main/java/uk/gov/di/ipv/cri/drivingpermit/certreminder/handler/CertExpiryReminderHandler.java, lib-dva/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dva/configuration/DvaConfiguration.java
Added missing certificate to expiry checks and cleaned up duplicate logging
=> LIME-498 - Adding certificate to expiry checks/log cleanup

.github/workflows/build.yml, .github/workflows/dailyDLSmokeTest.yml, .github/workflows/gradleBuildTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/pre-merge-integration-test.yml, .sdkmanrc, README.md, acceptance-tests/build.gradle, build.gradle, gradle.properties, infrastructure/lambda/template.yaml, lambdas/certexpiryreminder/build.gradle, lambdas/drivingpermitcheck/build.gradle, lambdas/issuecredential/build.gradle, lib-dva/build.gradle, lib-dvla/build.gradle, lib/build.gradle
Upgrade dl-api to java17
- [LIME-844](https://govukverify.atlassian.net/browse/LIME-844)
[LIME-844]: https://govukverify.atlassian.net/browse/LIME-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-844 Upgrade DL-api to java17

infrastructure/lambda/template.yaml
Updated cron expression for password rotation
To increase time between secret rotations
=> LIME-769: Minor update to extend window between secret rotations

infrastructure/lambda/template.yaml
Enabled parameter rotation in higher environments
To complete the enablement of password rotation
=> LIME-769: Cleanup following initial rotation

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/dailyDLSmokeTest.yml, .github/workflows/gradleBuildTest.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/pre-merge-integration-test.yml
Update workflows to:
* remove deprecations
* remove rusty actions
* implement dev-platform actions
* add dependabot for workflow actions
The github workflows
* remove deprecations
* remove rusty actions
* implement dev-platform actions
* add dependabot for workflow actions
- [IPS-447](https://govukverify.atlassian.net/browse/IPS-447)
- [IPS-480](https://govukverify.atlassian.net/browse/IPS-480)
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
- 
[IPS-447]: https://govukverify.atlassian.net/browse/IPS-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-480]: https://govukverify.atlassian.net/browse/IPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-503]: …
=> IPS-480 update workflows

.github/workflows/pre-merge-checks.yml
Version update missed in previous update
- [IPS-447](https://govukverify.atlassian.net/browse/IPS-447)
- [IPS-480](https://govukverify.atlassian.net/browse/IPS-480)
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
[IPS-447]: https://govukverify.atlassian.net/browse/IPS-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-480]: https://govukverify.atlassian.net/browse/IPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-503]: https://govukverify.atlassian.net/browse/IPS-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ips-447 add missed action version update

acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicence.feature
Removed background steps that were duplicated between tests
To fix break in the build
=> LIME-993: Removed duplicate steps causing tests to fail

.github/workflows/pre-merge-checks.yml, lambdas/issuecredential/build.gradle, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/domain/ThirdPartyAddress.java, lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/service/DocumentCheckRetrievalService.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/IssueCredentialHandlerTest.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/utils/Injector.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/utils/MockHttpServer.java, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/pact/utils/PreLambdaHandler.java
A new testing file has been added which includes scenarios and outcomes from DL CRI
To test against what has been agreed, and what our VC should contain, and ensure we don't deviate from it.
- [LIME-989](https://govukverify.atlassian.net/browse/LIME-989)
[LIME-989]: https://govukverify.atlassian.net/browse/LIME-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-989 adding contract tests for DL scenarios

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/Common/DLCommon.feature
Identified the methods that were missing the assert statements and updated the methods to include assert.
=> LIME-889 added the missing assert statements

acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicence.feature
Updated test scenarios for both DVLA/DVA
=> LIME-994 - Renaming test scenarios DL API

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java
Updated test data creation to remove bulk from pre written test data subjects to allow test data to be written without having to create a new subject
To upgrade and update the test framework
- [LIME-1060](https://govukverify.atlassian.net/browse/LIME-1060)
[LIME-1060]: https://govukverify.atlassian.net/browse/LIME-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Lime 1060 - Updated test data creation DL

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DLProveYourIdentityFullJourneyPageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DLProveYourIdentityFullJourneyStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVAProveIdentityFullJourney.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLAProveIdentityFullJourney.feature
Updated Driving licence DVLA and DVA E2E tests to run with the updated orchestrator stub.
=> LIME-1057 Updated driving licence E2E tests to work with the updated orchestrator stub

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DVLAAndDVADrivingLicenceStepDefs.java, acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/step_definitions/DrivingLicenceStepDefs.java, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVA/DVADrivingLicence.feature, acceptance-tests/src/test/resources/features/UKDrivingLicence/DVLA/DVLADrivingLicence.feature
- Updated DVLA & DVA step definitions with new ones
- Added new page objects
- To make test data more visible
- [LIME-1065](https://govukverify.atlassian.net/browse/LIME-1065)
[LIME-1065]: https://govukverify.atlassian.net/browse/LIME-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1065 - Replaced existing step definitions with new ones

acceptance-tests/build.gradle, build.gradle, deploy.sh, infrastructure/lambda/private-api.yaml, infrastructure/lambda/template.yaml
Updated Common-libs version and adding changes for cloudfront headers to template.
The new version enables compatibility for cloudfront.
- [LIME-1115](https://govukverify.atlassian.net/browse/LIME-1115)
[LIME-1115]: https://govukverify.atlassian.net/browse/LIME-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1115 Updating Common-libs version

lib-dva/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dva/configuration/DvaCryptographyServiceConfiguration.java, lib-dva/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dva/service/DVACloseableHttpClientFactory.java
Changing parameter paths to pull in new certificate values
=> Changing parameter paths for new certificates

build.gradle
Upgrading version changes for powertools in build.gradle, and using the same version throughout. AWS Metric version removed so to rely on powertools.
- [LIME-1190](https://govukverify.atlassian.net/browse/LIME-1190)
[LIME-1190]: https://govukverify.atlassian.net/browse/LIME-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1190 updating Powertools version to 1.18.0

infrastructure/lambda/template.yaml, lib-dva/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/dva/configuration/DvaConfiguration.java
Toggled on the use of the private CA
To enable the transition to a new private CA
=> LIME-1154: Toggling on the private ca store

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, .pre-commit-config.yaml
- Add linting step
- Code quality control
- [IPS-1132](https://govukverify.atlassian.net/browse/IPS-1132)
[IPS-1132]: https://govukverify.atlassian.net/browse/IPS-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1132: Add linting

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicenceAPIPage.java, build.gradle, lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/VerifiableCredentialServiceTest.java
Updated cri-lib version reference to latest
=> LIME-1271 - Updating lib version reference

lambdas/drivingpermitcheck/src/main/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandler.java, lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/handler/DrivingPermitHandlerTest.java, lib/src/main/java/uk/gov/di/ipv/cri/drivingpermit/library/metrics/Definitions.java
Added metrics to track the value of context
=> LIME-1286 - Adding metrics for tracking context values

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-for-build.yml, acceptance-tests/Dockerfile-traffictest, acceptance-tests/run-traffic-tests.sh
- Create ECR and workdflow for Traffic test
- Create ECR and workdflow for Traffic test
Create ECR and workdflow for Traffic test
- [IPS-1256](https://govukverify.atlassian.net/browse/IPS-1256)
[IPS-1256]: https://govukverify.atlassian.net/browse/IPS-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1256: Create ECR and workdflow for Traffic test

.secrets.baseline, README.md, deploy.sh, infrastructure/lambda/private-api.yaml, infrastructure/lambda/public-api.yaml, infrastructure/lambda/template.yaml
- Added LambdaCanaryDeployment preference on updated the pipeline
- Added Code Deploy Service role to allow code deploy
- Set LambdaDeploymentPreference to AllAAatOnce
- Updated lambda functions with the canary deployment configurations
- Added additional alarms for Lambda errors and 5xx errors with lower threshold
- Implement Lambda canary deployment for DL CRI
- Implement Lambda canary deployment for DL CRI
- Implement Lambda canary deployment for DL CRI
- [IPS-1112](https://govukverify.atlassian.net/browse/IPS-1112)
Code deploy screen:
Lambda canary deployment "AllAtOnce"
Lambda canary deployment "Canary10Percent5Minutes"
Lambda Canary deployment rollback test
[LIME-1112]: https://govukverify.atlassian.net/browse/LIME-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> IPS-1112: Implement Lambda canary deployment for Driver License

.github/dependabot.yml
Minor fix to dependabot grouping format to ensure grouping works. 
Previous format believed to be incorrect
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1229 minor fix to dependabot grouping

.github/workflows/deploy-branch.yml, .github/workflows/post-merge-deploy-acm-to-dev.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-acm-for-build.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/run-pre-merge-integration-tests.yml
Pin sam cli version in pre and post merge to the same version.
To control the cadence of updates
- [LIME-1603](https://govukverify.atlassian.net/browse/LIME-1603)
[LIME-1603]: https://govukverify.atlassian.net/browse/LIME-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1603 Pin sam cli version in pre and post merge to the same version.

.secrets.baseline, infrastructure/lambda/template.yaml
Enabling Snapstart, this PR is to be merged after - https://github.com/govuk-one-login/ipv-cri-dl-api/pull/423
=> LIME-1441 - Enabling Snapstart

infrastructure/lambda/template.yaml
Enabling snapstart for DL in int/prod, this PR is to be a fast follow to https://github.com/govuk-one-login/ipv-cri-dl-api/pull/426
=> LIME-1443 - Enabling Snapstart for DL (int/Prod)

acceptance-tests/src/test/java/gov/di_ipv_drivingpermit/pages/DrivingLicencePageObject.java
Renaming submitButton id to continue in tests in order to match the renamed id in the Frontend.
- [LIME-1758](https://govukverify.atlassian.net/browse/LIME-1758)
[LIME-1758]: https://govukverify.atlassian.net/browse/LIME-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1758: Renaming submitButton id to continue for tests.

.secrets.baseline, infrastructure/lambda/template.yaml
Added FMSRegionalPolicy and CustomPolicy tags to API Gateway resources.
Added IsDevOrBuildOrStaging conditional in order to add tags to lower environments.
Needed as part of transitioning FMS WAF rule enforcement.
- [LIME-1889](https://govukverify.atlassian.net/browse/LIME-1889)
[LIME-1889]: https://govukverify.atlassian.net/browse/LIME-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1889 Add FMS tags for custom WAF policy in dev/build/staging

.github/workflows/check-pr.yml, .github/workflows/cleanup-manually-deployed-dev-stacks.yml, .github/workflows/cleanup-pre-merge-stacks.yml, .github/workflows/cleanup-preview-stacks.yml, .github/workflows/delete-preview-stacks.yml, .github/workflows/deploy-branch.yml, .github/workflows/post-merge-deploy-acm-to-dev.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/post-merge-package-acm-for-build.yml, .github/workflows/post-merge-package-for-build.yml, .github/workflows/post-merge-sonar-scan.yml, .github/workflows/run-java-build-check.yml, .github/workflows/run-java-style-check.yml, .github/workflows/run-pact-tests.yml, .github/workflows/run-pre-merge-integration-tests.yml, .github/workflows/run-sonar-scan.yml, .github/workflows/run-unit-tests.yml, .github/workflows/smoke-test-build.yml
##What changed
updated workflow github-actions to pin the version
##Why did it change
SonarQube cloud Quality gate is failing the due to dependency version tagging. It is recommended to use the complete commit hash to pin the version when using third-party actions and workflows.
- [LIME-1909](https://govukverify.atlassian.net/browse/LIME-1909)
[LIME-1909]: https://govukverify.atlassian.net/browse/LIME-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1909 Add full SHA to github-actions
